apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-bot
  labels:
    app: train-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-bot
  template:
    metadata:
      labels:
        app: train-bot
    spec:
      containers:
        - name: train-bot
          image: ghcr.io/niuguy/train-bot:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: train-bot-secrets
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            exec:
              command: ["pgrep", "-f", "python -m train_bot"]
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            exec:
              command: ["pgrep", "-f", "python -m train_bot"]
            initialDelaySeconds: 30
            periodSeconds: 60
